### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by vzabawski** [arnobroekhof/puppet-elasticsearch#1]
I've installed elasticsearch reporter and can't get it working. Although elasticsearch.yaml config is placed in a proper location and configured (as I think) properly I'm getting "Connection refused" in puppet log.

`2017-07-07 13:09:11,390 ERROR [qtp141066584-64] [puppetserver] Puppet Report processor failed: Connection refused - Connection refused`

Here's my config file:

```
---
:elasticsearch_server: 'http://192.168.250.7'
:elasticsearch_port: '9200'
:elasticsearch_index: 'puppet'
:elasticsearch_type: 'report'
```
I can telnet elasticsearch without any problems:

`
[vagrant@puppetserver ~]$ telnet 192.168.250.7 9200
Trying 192.168.250.7...
Connected to 192.168.250.7.
Escape character is '^]'.
`

Although this repo seems to be abandoned, could you please at least help me to debug connection string that Tire uses to connect to the server? I think this may be the root cause.

**Comment by vzabauski** [comment]
Update.
It works fine if Elasticsearch runs on the same server with Puppet Server.
